- id: isort
  name: isort
  entry: poetry run isort .
  pass_filenames: false
  language: python
  types: [python]
- id: black
  name: black
  entry: poetry run black .
  language: python
  types: [python]
- id: mypy
  name: mypy
  entry: poetry run mypy .
  language: python
  types: [python]
